//! Verification utilities for Lotus-Miner.
//!
//! This module provides utilities for verifying Lotus-Miner startup and functionality.

use std::error::Error;
use std::thread;
use std::time::Duration;
use tracing::info;

use super::constants::{MINER_API_CHECK_DELAY_SECS, PORT_WAIT_TIMEOUT_SECS};
use crate::commands::start::step::SetupContext;
use crate::docker::builder::ContainerRunBuilder;
use crate::docker::containers::{lotus_container_name, lotus_miner_container_name};
use crate::docker::wait_for_port;
use crate::utils::retry::{retry_with_fixed_delay, DEFAULT_MAX_RETRIES, DEFAULT_RETRY_DELAY_SECS};

// Additional timing constant for API file wait
const API_FILE_TIMEOUT_SECS: u64 = 120;
const API_FILE_CHECK_INTERVAL_MS: u64 = 500;

/// Get the Lotus-Miner container name from context
fn get_container_name(context: &SetupContext) -> Result<String, Box<dyn Error>> {
    let run_id = context.run_id();
    Ok(lotus_miner_container_name(run_id))
}

/// Get the Lotus container name from context
fn get_lotus_container_name(context: &SetupContext) -> Result<String, Box<dyn Error>> {
    let run_id = context.run_id();
    Ok(lotus_container_name(run_id))
}

/// Check if lotus-miner is responsive
pub fn check_miner_api(context: &SetupContext) -> Result<(), Box<dyn Error>> {
    let container_name = get_container_name(context)?;

    // Try to execute a simple lotus-miner command via docker exec
    let key = format!("lotus_miner_api_check_{}", container_name);
    let output = ContainerRunBuilder::exec(&container_name)
        .cmd(&[
            "/usr/local/bin/lotus-bins/lotus-miner",
            "version",
        ])
        .run_logged(context, &key)?;

    if !output.status.success() {
        return Err(format!(
            "Lotus-Miner API check failed: {}",
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }

    Ok(())
}

/// Check if tipsets are being generated by waiting and comparing chain heights
pub fn check_tipset_generation(context: &SetupContext) -> Result<(), Box<dyn Error>> {
    let lotus_name = get_lotus_container_name(context)?;

    // Get initial chain height
    let key = format!("lotus_miner_chain_height_check_1_{}", lotus_name);
    let output1 = ContainerRunBuilder::exec(&lotus_name)
        .cmd(&[
            "/usr/local/bin/lotus-bins/lotus",
            "chain",
            "list",
            "--count=1",
        ])
        .run_logged(context, &key)?;

    if !output1.status.success() {
        return Err("Failed to get initial chain height".into());
    }

    let chain_output1 = String::from_utf8_lossy(&output1.stdout);
    let height1 = parse_chain_height(&chain_output1)?;

    retry_with_fixed_delay(
        || {
            // Get new chain height
            let key = format!("lotus_miner_chain_height_check_{}", lotus_name);
            let output2 = ContainerRunBuilder::exec(&lotus_name)
                .cmd(&[
                    "/usr/local/bin/lotus-bins/lotus",
                    "chain",
                    "list",
                    "--count=1",
                ])
                .run_logged(context, &key)?;

            if !output2.status.success() {
                return Err("Failed to get new chain height".into());
            }

            let chain_output2 = String::from_utf8_lossy(&output2.stdout);
            let height2 = parse_chain_height(&chain_output2)?;

            if height2 > height1 {
                info!("✓ Chain is progressing (height {} -> {})", height1, height2);
                Ok(())
            } else {
                Err(format!("Chain height still at {}", height1).into())
            }
        },
        DEFAULT_MAX_RETRIES,
        DEFAULT_RETRY_DELAY_SECS,
        "Chain progression verification",
    )
    .map_err(|_| {
        format!(
            "Chain is not progressing. Height remained at {} after {} attempts.",
            height1, DEFAULT_MAX_RETRIES,
        )
    })?;

    Ok(())
}

/// Perform all post-execution verifications for Lotus-Miner
pub fn perform_post_execution_verification(
    context: &SetupContext,
    volumes_dir: &std::path::Path,
) -> Result<(), Box<dyn Error>> {
    info!("Verifying Lotus-Miner startup...");

    // 1. Wait for API port to be available
    let miner_api_port: u16 = context
        .get("lotus_miner_api_port")
        .ok_or("Lotus-Miner API port not found in context")?
        .parse()?;

    info!("Waiting for Lotus-Miner API port {}...", miner_api_port);
    wait_for_port(miner_api_port, PORT_WAIT_TIMEOUT_SECS)?;
    info!("✓ Lotus-Miner API port is open");

    // 2. Wait for API file to be created (this is the critical step)
    wait_for_miner_api_file(volumes_dir)?;

    // 3. Check API responsiveness
    info!("Checking Lotus-Miner API responsiveness...");
    check_miner_api(context)?;
    info!("✓ Lotus-Miner API is responsive");

    // 4. Check tipset generation
    info!("Checking tipset generation...");
    check_tipset_generation(context)?;
    info!("✓ Tipset generation verified");

    info!("✓ Lotus-Miner verification complete");
    Ok(())
}

/// Parse chain height from lotus chain list output
/// Expected format: "5: (Nov 26 12:05:25) [ bafy...: t01000, ]"
fn parse_chain_height(output: &str) -> Result<u64, Box<dyn Error>> {
    // Get first line and extract the number before the colon
    if let Some(first_line) = output.lines().next() {
        if let Some(colon_pos) = first_line.find(':') {
            let height_str = first_line[..colon_pos].trim();
            return height_str
                .parse::<u64>()
                .map_err(|e| format!("Failed to parse height '{}': {}", height_str, e).into());
        }
    }
    Err("Could not parse chain height from output".into())
}

/// Wait for the Lotus-Miner API file to be created
fn wait_for_miner_api_file(volumes_dir: &std::path::Path) -> Result<(), Box<dyn Error>> {
    info!("Waiting for Lotus-Miner API file to be created...");

    let miner_data_dir = volumes_dir.join("lotus-miner-data");
    let api_file = miner_data_dir.join("api");

    let start = std::time::Instant::now();
    let timeout = Duration::from_secs(API_FILE_TIMEOUT_SECS);

    while !api_file.exists() {
        if start.elapsed() > timeout {
            return Err(format!(
                "Timeout waiting for Lotus-Miner API file at {}",
                api_file.display()
            )
            .into());
        }
        thread::sleep(Duration::from_millis(API_FILE_CHECK_INTERVAL_MS));
    }

    info!("✓ Lotus-Miner API file created");

    // Wait a bit more for the API to fully initialize
    thread::sleep(Duration::from_secs(MINER_API_CHECK_DELAY_SECS));

    Ok(())
}
